[package]
name = "testspecgen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.56"
serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = "0.8.23"
clap = { version = "3.1.8", features = ["derive", "env"] }
mktemp = "0.4.1"
xlsxwriter = "0.3.5"
regex = "1.5.5"
