[package]
name = "testspecgen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
serde = { version = "1.0.138", features = ["derive"] }
serde_yaml = "0.8.25"
clap = { version = "3.2.8", features = ["derive", "env"] }
mktemp = "0.4.1"
xlsxwriter = "0.3.5"
regex = "1.6.0"
